services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: always
    # command: uvicorn app.main:app --host 127.0.0.1 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    restart: always
    # command: npm run dev # 開発モードで起動
